-- USERS
CREATE TABLE users(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

-- MUSCLE GROUPS
CREATE TABLE muscle_groups(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  description VARCHAR(500)
);

-- EXERCISES
CREATE TABLE exercises(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description VARCHAR(1000),
  category VARCHAR(100) NOT NULL,
  muscle_group_id BIGINT,
  CONSTRAINT fk_exercise_mg FOREIGN KEY (muscle_group_id) REFERENCES muscle_groups(id)
);

-- WORKOUTS
CREATE TABLE workouts(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  title VARCHAR(255) NOT NULL,
  notes TEXT,
  scheduled_at TIMESTAMP,
  status VARCHAR(20),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_workout_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_workouts_user_date ON workouts(user_id, scheduled_at);

-- WORKOUT ITEMS
CREATE TABLE workout_items(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workout_id BIGINT NOT NULL,
  exercise_id BIGINT NOT NULL,
  sets INT NOT NULL,
  reps INT NOT NULL,
  weight NUMERIC(6,2),
  rest_seconds INT,
  order_index INT,
  CONSTRAINT fk_item_workout FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE,
  CONSTRAINT fk_item_exercise FOREIGN KEY (exercise_id) REFERENCES exercises(id)
);
